[package]
name = "rr-mux"
version = "0.1.0"
authors = ["Ryan Kurte <ryankurte@gmail.com>"]
edition = "2018"
repository = "https://github.com/ryankurte/rust-rr-mux"
license = "MIT"

[dependencies]
futures = "0.1.25"
log = "0.4.6"

